/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-02-21

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4_discovery.h"
#include "serial.h"
#include "vt100.h"
#include "interface.h"
#include "vaisseau.h"
#include <unistd.h>

#define TOUCHE serial_get_last_char()

uint8_t t = 40;
static int x_start = 4;
static int x_start2 = 11;
static int y_ennemis = 5;
static int y_ennemis2 = 10;
static int i = 0;
static int compteur = 0;
static int y_tir = 21;

int main(void)
{

	serial_init(115200);
	vt100_clear_screen();
	Start_Menu();
	Bordure();

	while ( TOUCHE == -1)
	{

	}

	restart:

	vt100_clear_screen();
	Bordure();

	mouvement:

	while (1)
	{
		Affichage_Ennemis(Set_Pos_Ennemis(x_start, 15, 1), y_ennemis, "/::\\",
				1);
		Affichage_Ennemis(Set_Pos_Ennemis(x_start2, 15, 2), y_ennemis2, "/::\\",
				2);

		x_start = borne_gauche(x_start);

		int touche = serial_get_last_char();
		Place_Caractere(t, 22, "/<I>\\");

		if (touche == 'd' && t < 74)
		{
			Place_Caractere(t, 22, "     ");
			t += 2;
			Place_Caractere(t, 22, "/<I>\\");
		}

		if (touche == 'q' && t > 3)
		{
			Place_Caractere(t, 22, "     ");
			t -= 2;
			Place_Caractere(t, 22, "/<I>\\");
		}

		if (touche == 'z')
		{
			Tire_vaisseau(t, y_ennemis, y_ennemis2, y_tir);
			y_tir -= 1;
			if (y_tir == 2)
			{
				y_tir = 21;
			}
		}

		if (touche == 'r')
		{
			t = 40;
			restart();
			x_start = 4;
			x_start2 = 11;
			y_ennemis = 5;
			y_ennemis2 = 10;
			compteur = 0;
			goto restart;
		}

		if (i == 40)
		{

			if (compteur == 0)
			{
				Place_Caractere(2, y_ennemis,
						"                                                                              ");
				Place_Caractere(2, y_ennemis2,
						"                                                                              ");

				if (x_start == 9)
				{
					compteur = 1;
					y_ennemis += 1;
					y_ennemis2 += 1;
					goto mouvement;
				}

				x_start += 1;
				x_start2 += 1;
			}

			if (compteur == 1)
			{
				Place_Caractere(2, y_ennemis,
						"                                                                              ");
				Place_Caractere(2, y_ennemis2,
						"                                                                              ");
				if (x_start == 2)
				{
					compteur = 0;
					y_ennemis += 1;
					y_ennemis2 += 1;
					goto mouvement;
				}

				x_start -= 1;
				x_start2 -= 1;
			}

		}
		i = (i + 1) % 41;
	}
}

/*
 * Callback used by stm32f4_discovery_audio_codec.c.
 * Refer to stm32f4_discovery_audio_codec.h for more info.
 */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size)
{
	/* TODO, implement your code here */
	return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
uint16_t EVAL_AUDIO_GetSampleCallBack(void)
{
	/* TODO, implement your code here */
	return -1;
}
